parameters:
#    public.example.class: Mobility\PublicBundle\Example

services:
#    public.example:
#        class: %public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
