<?php

namespace Mobility\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EcoActorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoActorsRepository extends EntityRepository
{
}
