<?php

namespace Mobility\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActorRepository extends EntityRepository
{
}
